name: 📚 Documentation
description: Report an issue in the project's documentation or README.md file.
title: "[Documentation Addition]: "
labels: ["documentation", "No Code" ]

body:
  - type: markdown
    attributes:
      value: |
        📚 **Document Request / Updation **

        Thanks for taking the time to fill out this documentation deficiency report! :memo:

        :information_source: Before submitting the report, please make sure to read our contributing guidelines. By submitting this issue, you agree to follow our guidelines. :book:

        :link: [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md)

  - type: textarea
    id: documentation-description
    attributes:
      label: Also, describe the documentation you want to add. ✍️
      description: Enter a brief description about the deficit documentation that you want to add.
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Description"
      render: bash
    validations:
      required: true
      
  - type: dropdown
    id: contribution
    attributes:
      label: Are you contributing for a program?
      multiple: true
      options:
        - GSSoC23
        - Other
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contributing guidelines. Please read our [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md).
      options:
        - label: I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.
          required: true
