name: Add Labels to Issues and PRs

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    strategy:
      matrix:
        template: [bug_report.yml, feature.yml, doc.yml]

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      - name: Add 'gssoc23' label to Issues based on policy
        uses: redhat-plumbers-in-action/advanced-issue-labeler@main
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          template: ${{ matrix.template }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add 'gssoc23' Label to PRs
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const label = 'gssoc23';

            const addLabelParams = {
              owner: owner,
              repo: repo,
              issue_number: prNumber,
              labels: [label]
            };

            await github.issues.addLabels(addLabelParams);

            console.log(`Added the 'gssoc23' label to PR #${prNumber}.`);
